istio:
  ingressGateways:
    public-ingressgateway:
      type: "NodePort"  #MxNxPx
    passthrough-ingressgateway:
      type: "NodePort"  #MxNxPx

neuvector:
  enabled: false  #MxNxPx

kyvernopolicies:
  values:
    policies:
      restrict-host-path-mount:
        parameters:
          allow:
           - /var/lib/rancher/k3s/storage/*
      restrict-host-path-mount-pv:
        parameters:
          allow:
           - /var/lib/rancher/k3s/storage/*
      restrict-host-path-write:
        parameters:
          allow:
           - /var/lib/rancher/k3s/storage/*

#kyvernopolicies:
#  values:
#    policies:
#      restrict-host-path-mount:
#        enabled: false
#      restrict-host-path-mount-pv:
#        enabled: false
#      restrict-host-path-write:
#        enabled: false
#      restrict-volume-types:
#        enabled: false

#kyvernopolicies:
#  values:
#    policies:
#      restrict-host-path-mount:
#        exclude:
#          any:
#          - resources:
#              names:
#              - monitoring-monitoring-grafana*
#              namespaces:
#              - monitoring
#          - resources:
#              names:
#              - prometheus-monitoring-monitoring-kube-prometheus*
#              namespaces:
#              - monitoring
#      restrict-volume-types:
#        exclude:
#          any:
#          - resources:
#              names:
#              - monitoring-monitoring-grafana*
#              namespaces:
#              - monitoring
#          - resources:
#              names:
#              - prometheus-monitoring-monitoring-kube-prometheus*
#              namespaces:
#              - monitoring
#      restrict-host-path-mount-pv:
#        exclude:
#          any:
#          - resources:
#              names:
#              - monitoring-monitoring-grafana*
#          - resources:
#              names:
#              - prometheus-monitoring-monitoring-kube-prometheus*
